// Senate
export const GET_SENATORS = 'GET_SENATORS';
export const SENATORS_ERROR = 'SENATORS_ERROR';
export const GET_MINI_SENATORS = 'GET_MINI_SENATORS';
export const MINI_SENATORS_ERROR = 'MINI_SENATORS_ERROR';
// Congress
export const GET_CONGRESS = 'GET_CONGRESS';
export const CONGRESS_ERROR = 'CONGRESS_ERROR';
export const GET_MINI_CONGRESS = 'GET_MINI_CONGRESS';
export const MINI_CONGRESS_ERROR = 'MINI_CONGRESS_ERROR';
// Preferences
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const PREFERENCES_ERROR = 'PREFERENCES_ERROR';
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES';
export const UPDATE_PREFERENCES_ERROR = 'UPDATE_PREFERENCES_ERROR';
// Details
export const GET_SECTORS = 'GET_SECTORS';
export const SECTORS_ERROR = 'SECTORS_ERROR';
export const GET_CONTRIBUTORS = 'GET_CONTRIBUTORS';
export const CONTRIBUTORS_ERROR = 'CONTRIBUTORS_ERROR';
// User
export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_GOOGLE_UID = 'SET_GOOGLE_UID';
export const GET_SPONSORS = 'GET_SPONSORS';
export const SPONSORS_ERROR = 'SPONSORS_ERROR';
export const GET_SENATOR_DETAILS = 'GET_SENATOR_DETAILS';
export const SENATOR_DETAILS_ERROR = 'SENATOR_DETAILS_ERROR';
export const GET_CONGRESS_DETAILS = 'GET_CONGRESS_DETAILS';
export const CONGRESS_DETAILS_ERROR = 'CONGRESS_DETAILS_ERROR';
