// Senate
export const GET_SENATORS = 'GET_SENATORS';
export const SENATORS_ERROR = 'SENATORS_ERROR';
export const GET_SENATORS_BY_STATE = 'GET_SENATORS_BY_STATE';
export const SENATORS_BY_STATE_ERROR = 'GET_SENATORS_BY_STATE_ERROR';

// Congress
export const GET_CONGRESS = 'GET_CONGRESS';
export const CONGRESS_ERROR = 'CONGRESS_ERROR';
// Preferences
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const PREFERENCES_ERROR = 'PREFERENCES_ERROR';
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES';
export const UPDATE_PREFERENCES_ERROR = 'UPDATE_PREFERENCES_ERROR';
// Details
export const GET_SECTORS = 'GET_SECTORS';
export const SECTORS_ERROR = 'SECTORS_ERROR';
export const GET_CONTRIBUTORS = 'GET_CONTRIBUTORS';
export const CONTRIBUTORS_ERROR = 'CONTRIBUTORS_ERROR';
// User
export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR';
