export class Congress {
  constructor(
    public id: number,
    public proPublicaId: string,
    public title: string,
    public shortTitle: string,
    public apiUrl: string,
    public firstName: string,
    public middleName: string,
    public lastName: string,
    public suffix: string,
    public dateOfBirth: string,
    public gender: string,
    public party: string,
    public leadershipRole: string,
    public twitterAccount: string,
    public facebookAccount,
    youtubeAccount: string,
    govtrackId: number,
    cspanId: number,
    votesmartId: number,
    icpsrId: number,
    crpId: string,
    googleEntityId: string,
    fecCandidateId: string,
    url: string,
    rssUrl: string,
    contactForm: string,
    inOffice: boolean,
    //    @JsonProperty(value="cook_pvi")
    dwNominate: number,
    //    @JsonProperty(value="ideal_point")
    seniority: number,
    nextElection: string,
    totalVotes: number,
    missedVotes: number,
    totalPresent: number,
    lastUpdated: string,
    ocdId: string,
    office: string,
    phone: string,
    //    @JsonProperty(value="fax")
    state: string,
    district: string,
    atLarge: boolean,
    geoId: string,
    missedVotesPct: number,
    votesWithPartyPct: number,
    votesAgainstPartyPct: number,
    imageUrl: string,
  ) {}
}
